name: "Cloudflare Purge Cache"
description: "Purge a zone's cache via the Cloudflare API"
author: jakejarvis
inputs:
  cloudflareZone:
    description: "The Zone ID of your domain, which can be found in the right sidebar of your domain's overview page on the Cloudflare dashboard."
    required: true
  cloudflareEmail:
    description: "The email address you registered your Cloudflare account with."
    required: true
  cloudflareKey:
    description: "Your Cloudflare API key."
    required: true
runs:
  using: docker
  image: Dockerfile
branding:
  color: orange
  icon: trash-2
